[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 500

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#ff00a4"
backgroundColor = "#000000"
secondaryBackgroundColor = "#0a0a0a"
textColor = "#ffffff"
font = "sans serif"
